### PR TITLE
Cleanup and facebook share image

### PR DESCRIPTION
**Pull request by snowflakekiller**
added a facebook share image... just overlaid the Rapid River logo over the current BG. Feel free to change it, the tags are set. 

Also removed image files that are leftovers from the template

### CODE REVIEW

**Comment by snowflakekiller** [comment]
@calumhalcrow

**Comment by calumhalcrow** [comment]
@snowflakekiller thanks for taking the initiative to do some cleanup :-)

BTW, you can assign PRs to me for review - more "proper" ;-)

**Comment by snowflakekiller** [comment]
@calumhalcrow cool will do. Did so retroactively for all the previous PRs for tracking purposes

**Comment by calumhalcrow** [comment]
👍

**Pull request merged**
