### PR TITLE
Feature | Unpublish data engineering service

### PR DESCRIPTION
**Pull request by monsteronfire**
The changes in this PR are in preparation for the services page to go live, it includes:
1. Removal of data engineering service
2. Linking services nav link to standalone page instead of CTA on homepage

### CODE REVIEW

**Comment by monsteronfire** [comment]
@calumhalcrow Please have a look at the changes and let me know if you have feedback.

**Comment by monsteronfire** [comment]
@calumhalcrow, thanks for the feedback. 💯  Looking at it now.

**Comment by monsteronfire** [comment]
@calumhalcrow That "Go back..." button style seems like a Chrome problem. Sorry I didn't catch that on Firefox.

**Comment by monsteronfire** [comment]
@calumhalcrow I've addressed all the feedback you left and also made some further fixes to improve the layout on mobile. Please review when you get some time. Thanks! 🌸

**Comment by calumhalcrow** [comment]
I've merged this. I wanted to get the content published, as there is someone who wants to read it 😅But I do have a couple of further cosmetic items I want to give feedback on. I'll send more info about that shortly...

**Comment by monsteronfire** [comment]
@calumhalcrow OK 👍

**Pull request merged**
