### PR TITLE
Feature | Big restructure with Bootstrap upgrade

### PR DESCRIPTION
**Pull request by monsteronfire**
This PR includes:

1. Bootstrap upgrade
2. Introduction of SCSS
3. Folder clean-up and restructure
4. Services page layout
5. Services post layout
6. Services collection
7. Services CTA on homepage
8. Image optimisation
9. Refined Main Nav styles
10. Content for `project rescue` service post
11. Temporary unlinked services page

### CODE REVIEW

**Comment by carloslima** [comment]
```
commit 6203286b18026ee4fb8862784caeae19959d90cd
Author: Shaii Ong <monsteronfire@gmail.com>
Date:   Mon Oct 14 14:48:23 2019 +0800

    Standardise indentation across all pages
```
Have you considered adding a linter to the tests to ensure it stays standard? :-)

**Comment by carloslima** [comment]
I looked at the whole commit history and everything looked ok but I don't feel my input is meaningful here other than the one suggestion above. :P

**Comment by monsteronfire** [comment]
@carloslima, thanks for looking at it and leaving feedback.

As mentioned on Slack, I will open a new PR for the linter. :)

**Comment by calumhalcrow** [comment]
Hi Shaii - looking at the old vs. new Services section on the homepage, it feels to me that we're losing content and descriptions of what we do. The live homepage gives visitors some sense of the services we offer. The version on this PR doesn't appear to do that. What do you think?

Screenshot 2019-11-04 at 10 18 41 AM

**Comment by monsteronfire** [comment]
@calumhalcrow I will reinstate the old services CTA and put the new one back once we have content to support it.

**Comment by monsteronfire** [comment]
@calumhalcrow Old services CTA has been reinstated. 👍

**Pull request merged**
