### PR TITLE
Feature | Hire us page

### PR DESCRIPTION
**Pull request by monsteronfire**
This PR includes the following:

1. New "Hire Us" page
2. Removal of "Contact" form from homepage
3. Addition of "Hire Us CTA" on homepage
4. Updates to the form submission JS
5. Submission email change from `info@rrsoft.co` to `hire-us@rrsoft.co`
6. Placeholder copy for hire-us flow

### CODE REVIEW

**Comment by calumhalcrow** [comment]
Thanks Shaii, looks great! I have some feedback (I'll post each item in its own comment):

Looks like the "Tell Us More" button is throwing a JS error (is it just for me?):

Screenshot 2019-09-02 at 9 44 21 AM

**Comment by calumhalcrow** [comment]
The flow from the homepage "Tell Us More" goes to to the top of the Hire Us page. The user has to hop one more time (either via the "Get in Touch" button or by scrolling) to get to the contact form. Perhaps the "Tell Us More" button should go straight to the form?

**Comment by calumhalcrow** [comment]
I got an error when submitting the contact form. Could be that formspree isn't configured to send mail to hire-us@rrsoft.co?

Screenshot 2019-09-02 at 9 52 49 AM

**Comment by calumhalcrow** [comment]
On the contact form, should we indicate which fields are required and which are optional?

**Comment by monsteronfire** [comment]
@calumhalcrow, thanks for the feedback. I've addressed all but the formspree/form submission one. I will look into that shortly.

**Comment by carloslima** [comment]
Looks good :shipit:

**Comment by monsteronfire** [comment]
@calumhalcrow I've updated the form and tested it. Seems to be alright now.

**Pull request merged**
