### PR TITLE
Feature | Minor UI changes

### PR DESCRIPTION
**Pull request by monsteronfire**
This PR does the following:

1. Adds a section for `case studies` with dummy data
2. Moves `about` section to own stand-alone page
3. Makes slight changes to colours, font and images

Note: All new images are placeholders. Will update after feedback

### CODE REVIEW

**Comment by carloslima** [comment]
@monsteronfire I haven't loaded the site with your change but I like your clean commits :100: :1st_place_medal: 
And your github account is the best hahaha :fire:

**Comment by calumhalcrow** [comment]
wow, the landing page looks great! 😍

**Comment by jimmynguyc** [comment]
The new ` img/header-bg.jpg` needs to have higher definition. Buy the stock photo maybe?

**Comment by monsteronfire** [comment]
@jimmynguyc I'm planning on taking photos at the office and making our own.

**Comment by monsteronfire** [comment]
@calumhalcrow In the interest of moving this along quicker, I decided to save the photo-taking for another day and instead opted to make a higher-res version of the header image with some minor tweaks:

1. Removed some buildings from the skyline
2. Added a mock Slack UI to the laptop screen (with an Yih-En emoji - let me know if it is too big)

The actual images for case-studies have also been added. I have replaced most of the dummy text with actual text, I just need your help to improve it. Specific areas would be:

1. Project descriptions
2. Project tech

Thank you! 🐱

**Pull request merged**
