### PR TITLE
Feature | Blue headers

### PR DESCRIPTION
**Pull request by monsteronfire**
### This PR adds:
1. Updated header images
2. Updates header styles
3. Removal or outdated styles
4. Minor UI fixes

### To Test:
1. Follow the instructions in the README to start the project
2. Check that headers have all changed
3. Check that footer has changed too
4. Click on the phone number and address to test "callable" and "google mappable", respectively

### CODE REVIEW

**Comment by calumhalcrow** [comment]
The Get In Touch button on the homepage leads to a 404 for me @monsteronfire.

**Comment by calumhalcrow** [comment]
I noticed that the buttons in the new headers have a different font than other buttons. I guess that's part of the design transition and is something we can live with. Just mentioning that I saw it.

**Comment by calumhalcrow** [comment]
I see that individual job ads ([e.g. this one on localhost](http://localhost:4000/careers/senior-software-engineer/)) continue to use the old header.

**Comment by monsteronfire** [comment]
Thanks for the feedback, @calumhalcrow

**Comment by monsteronfire** [comment]
@calumhalcrow I've made more changes to the PR. Please take a look when you're able. Thanks!

**Pull request merged**
