### PR TITLE
Page | Case studies

### PR DESCRIPTION
**Pull request by monsteronfire**
**This PR includes:**
- a new Case Studies page design
- case study content and illustrations
- burger menu on the left
- a downgrade of the Jekyll image version
- updated hire us CTA design at bottom of case studies and services page
- a fix for horizontal scroll bug on hire us page
- a bunch of small UI fixes

**To test:**
- In your browser, resize width (or use Responsive Design Mode)
- make sure nothing is broken on small, medium, large screens

### CODE REVIEW

**Comment by monsteronfire** [comment]
Blergh. Just leaving a note here for posterity.

The Jekyll image I was using has had a bunch of changes made to it. The latest image stopped working, suddenly for some people.

There's an open issue on their github:
https://github.com/envygeeks/jekyll-docker/issues/268

I'm going to downgrade and use a previous image.

**Comment by calumhalcrow** [comment]
Looks great so far 😄

**Comment by monsteronfire** [comment]
@calumhalcrow I think this PR is ready to review. Just giving you a heads-up. Please take a look at it when you are able. Thanks!

**Comment by calumhalcrow** [comment]
> @calumhalcrow I think this PR is ready to review. Just giving you a heads-up. Please take a look at it when you are able. Thanks!

Will do soon...

**Comment by monsteronfire** [comment]
Thanks for doing UAT, @calumhalcrow! Merging now. 👍

**Pull request merged**
